/**
 * Reads the manifest generated by the thumbnail script.
 * Returns gallery data with orientation metadata for masonry layout.
 */
import { readFileSync, readdirSync, statSync } from 'fs';
import { join, extname, basename } from 'path';

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const MANIFEST_PATH = 'public/images/manifest.json';
const ORDER = ['Washington',  'SF', 'Peru', 'Thailand'];

export interface GalleryImage {
  filename: string;
  thumb: string;
  full: string;
  orientation: 'portrait' | 'landscape';
}

export interface Gallery {
  name: string;
  slug: string;
  images: GalleryImage[];
}

export function getGalleries(): Gallery[] {
  let manifest: Record<string, Array<{ filename: string; file: string; orientation: string }>>;

  try {
    manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'));
  } catch {
    // Fallback: scan directories without orientation data
    return getGalleriesFallback();
  }

  
  const galleries: Gallery[] = [];

  for (const [galleryName, images] of Object.entries(manifest)) {
    const galleryImages: GalleryImage[] = images.map((img) => ({
      filename: img.filename,
      thumb: `/images/thumbs/${galleryName}/${img.filename}.jpg`,
      full: `/images/fulls/${galleryName}/${img.file}`,
      orientation: img.orientation as 'portrait' | 'landscape',
    }));

    galleries.push({
      name: galleryName,
      slug: galleryName.toLowerCase(),
      images: galleryImages,
    });
  }

  if (ORDER.length > 0) {
    galleries.sort((a, b) => {
      const ai = ORDER.indexOf(a.name);
      const bi = ORDER.indexOf(b.name);
      return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
    });
  } else {
    galleries.sort((a, b) => a.name.localeCompare(b.name));
  }

  return galleries;
}

function getGalleriesFallback(): Gallery[] {
  const fullsDir = 'public/images/fulls';
  const entries = readdirSync(fullsDir);
  const galleries: Gallery[] = [];

  for (const entry of entries) {
    const entryPath = join(fullsDir, entry);
    if (!statSync(entryPath).isDirectory()) continue;

    const files = readdirSync(entryPath);
    const images: GalleryImage[] = files
      .filter((f) => IMAGE_EXTS.has(extname(f).toLowerCase()))
      .map((f) => ({
        filename: basename(f, extname(f)),
        thumb: `/images/thumbs/${entry}/${basename(f, extname(f))}.jpg`,
        full: `/images/fulls/${entry}/${f}`,
        orientation: 'landscape' as const,
      }));

    galleries.push({ name: entry, slug: entry.toLowerCase(), images });
  }
  
  if (ORDER.length > 0) {
    galleries.sort((a, b) => {
      const ai = ORDER.indexOf(a.name);
      const bi = ORDER.indexOf(b.name);
      return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
    });
  } else {
    galleries.sort((a, b) => a.name.localeCompare(b.name));
  }

  return galleries;
}
